/* DO NOT EDIT THIS FILE - it is machine generated */
#include <QtAndroidExtras/QAndroidJniObject>
#include "qdebug.h"

/* Header for class com_ahmed_QAndroidResultReceiver_jniExport_jniExport */

#ifndef _Included_com_ahmed_QAndroidResultReceiver_jniExport_jniExport
#define _Included_com_ahmed_QAndroidResultReceiver_jniExport_jniExport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ahmed_QAndroidResultReceiver_jniExport_jniExport
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ahmed_QAndroidResultReceiver_jniExport_jniExport_intMethod
  (JNIEnv *, jobject, jint);

JNIEXPORT jint JNICALL Java_com_ahmed_QAndroidResultReceiver_jniExport_jniExport_StringReceiver
  (JNIEnv *var1, jobject var2, jstring string);
#ifdef __cplusplus
}
#endif
#endif
