/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_qtproject_example_QAndroidResultReceiver_jniExport */

#ifndef _Included_org_qtproject_example_QAndroidResultReceiver_jniExport
#define _Included_org_qtproject_example_QAndroidResultReceiver_jniExport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_qtproject_example_QAndroidResultReceiver_jniExport
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_qtproject_example_QAndroidResultReceiver_jniExport_intMethod
  (JNIEnv *, jobject, jint);
#ifdef __cplusplus
}
#endif
#endif
